### ISSUE TITLE
generate arbitrary coproduct families, and their instances

### ISSUE THREAD

**Issue by fommil** [alexarchambault/scalacheck-shapeless#1]
https://github.com/typelevel/shapeless-contrib/issues/25

**Comment by milessabin** [comment]
The approach that @fommil and I had discussed was based on shapeless's [staging example](https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/staging.scala#L41) ... ie. use run time tree construction and compilation to create static types and values of those types "dynamically".

**Comment by alexarchambault** [comment]
(Late) update: I'll definitely have a look at that, don't know now exactly when though. If ever one of you is feeling like trying to do that in the mean time, please do.

**Comment by fommil** [comment]
no danger of that, my TODO list is getting ridiculous (not helped by the need to workaround typesafe being assholes with previously open source slick drivers)

**Comment by alexarchambault** [comment]
I was thinking about giving this a try using [Ammonite](https://github.com/lihaoyi/Ammonite) (or maybe my [fork of it](https://github.com/alexarchambault/ammonite-shell) in the first time) rather than what's in `scala.tools`.

In the idea I had of that, it's actually two problems in one:
* generating definitions for arbitrary case classes / ADT per se, so just code like `case class CC(...)` or `sealed trait ...`,
* and generating trees where these definitions would be put, e.g. they can be put in a singleton, but also in a class definition, like `class C { case class CC(i: Int) }; object CImpl extends C` then accessed via `CImpl.CC`).

A lot of variation is possible in the code generated by the second point:
* we can access the definitions through things like `val impl = new C` instead of `object CImpl extends C` for example,
* or there can be type parameters in the nesting class, like `class C[T] { case class CC(t: T) }`, or these can be type members,
* etc.

A lot of type class deriving libraries don't handle well complex cases where the types are not trivially accessible. It would be really interesting to be able to test that.

**Comment by alexarchambault** [comment]
The problem is that, basically, this amounts to generating arbitrary trees. I quickly tried to do that some time ago, but felt that I was somehow duplicating the tree API of scala-reflect... That's why I would have been interested in your opinion about this. (Do you think that would be worthwhile? Are there particular kinds of trees it would be interesting to generate? ...)

**Comment by fommil** [comment]
@alexarchambault awesome, great news that you're looking at this!

My priorities for such a generator would be:

1. simple sealed traits comprised of sealed traits, case objects and case classes of primitives.
2. extension mechanism to support additional members in case classes (e.g. Collections API, `File`, etc)
3. More esoteric family structures, such as recursive types and multiple inheritance.

If you come up with something before December, I can include your work in my Scala eXchange talk (assuming a. I get accepted b. you're ok with that) because I'll definitely be using this to test `spray-json-shapeless` and `s-express`.

**Comment by milessabin** [comment]
I'm actually going to look at doing something along these lines for the derived-cats project that I'll be publishing very shortly.

I'll probably do it as an independent thing, because I think there might be quite a few projects that would be interested in using it.

**Comment by alexarchambault** [comment]
@milessabin Great! Do you generate something like the arbitrary trees I was talking about? I have simple examples like these where `Generic` derivation fails.

**Comment by milessabin** [comment]
Arbitrary ADTs.

If you have an example where `Generic` fails I'd very much like to see it!

**Comment by alexarchambault** [comment]
@milessabin It's here: https://github.com/milessabin/shapeless/issues/417
